[project]
name = "wled-matrix-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.6",
    "httpx>=0.28.1",
    "jinja2>=3.1.4",
    "python-dotenv>=1.0.1",
    "uvicorn>=0.34.0",
]
